name: Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install
      run: npm install
    - name: config git
      env:
        email: ${{secrets.EMAIL}}
      run: |
        git config user.email env.email
        git config user.name "Yona168"
    - name: deploy
      run: npm run deploy
    
        
